APM-67: Init online banking
valitydev/checkout pull request #17
Opened 2022-02-03 08:03 UTC by KrickRay

2022-02-03 09:55 UTC, KeinAsylum requested changes

2022-02-03 09:55 UTC, KeinAsylum commented on src/app/components/app/modal-container/modal/form-container/online-banking-form/banks-list/banks-list.tsx
> +import styled from 'checkout/styled-components';
Похоже на наколеночное решение, такое не годится. Ожидал нормальный элемент управления, что-то вроде: https://ant.design/components/list/ только проще, под нашу специфику.

2022-02-15 16:44 UTC, KeinAsylum requested changes
* Загрузку service provider нужно производить в `initializeModel` saga, там есть весь необходимый контекст для вызова api методов;
* Нет проверок на состояние метаданных. Если неверно настроить метадату провайдеру, весь функционал onlinebanking сломается;

2022-02-15 16:44 UTC, KeinAsylum commented on src/app/components/app/modal-container/modal/form-container/online-banking-form/banks-list/banks-list.tsx
> +import { BankLogo } from 'checkout/components/app/modal-container/modal/form-container/online-banking-form/bank-logo';
!

2022-02-15 16:44 UTC, KeinAsylum commented on src/app/state/forms/online-banking-account-form-values.ts
> +    metadata: any;
1. Нужно затипизировать
2. Поле опционально

2022-02-15 16:46 UTC, KeinAsylum commented on src/app/backend/model/online-banking/service-provider-metadata.ts
> +    };
Не думаю, что хранить svg и цвет в domain config хорошая идея

2022-02-15 22:15 UTC, KrickRay commented on src/app/state/forms/online-banking-account-form-values.ts
> +    metadata: any;
1. так оно действительно `any`

2022-02-15 22:15 UTC, KrickRay commented on src/app/backend/model/online-banking/service-provider-metadata.ts
> +    };
src - путь до svg
backgroundColor зависит от svg
а какая хорошая?

2022-02-15 22:17 UTC, KrickRay commented
1. Что значит "нужно", каким образом мне это костылять в initializeModel? Сейчас getTerminalsPaymentMethods я точно знаю какие провайдеры мне загружать. Если речь про сайды эффекты, так вся сага как раз про это
2. Я как-то особо не смог сломать, про какие проверки речь? Чтобы валидировать JSON нам надо что-то еще придумывать или либу использовать

2022-02-16 15:44 UTC, KeinAsylum requested changes
* Новому методу оплаты не выставляется приоритет (функция setPriority, должен идти после ApplePay);
* Отсутствует анимация при попытке оплаты с неверно заполненными данными;
* Логирование должно происходить с использованием logPrefix;
* Не обрабатывается случай, когда `getServiceProviderByID` возвращает ошибку (404 или 500). Ошибка должна приводить к недоступности оплаты через конкретного провайдера;

2022-02-16 15:44 UTC, KeinAsylum commented on src/app/sagas/initialize-app/initialize-available-payment-methods/get-payment-methods/get-terminals-payment-methods.ts
> +export function getTerminalsPaymentMethods(
Логику с assert на состояние метаданных лучше перенести сюда. Тут уже присутствуют assert на неверные параметры интеграции. Для других методов оплаты сделано точно также.

2022-02-17 12:58 UTC, KeinAsylum approved these changes

2022-02-17 13:00 UTC, merged